version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./rfi-docs:/app/rfi-docs
    environment:
      - PORT=8001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped 